<?php

define('CURLY_BUSINESS_VERSION', '2.0.3');
define('CURLY_BUSINESS_ABS_PATH', dirname(__FILE__));
define('CURLY_BUSINESS_REL_PATH', dirname(plugin_basename(__FILE__)));
define('CURLY_BUSINESS_URL_PATH', plugin_dir_url(__FILE__));
define('CURLY_BUSINESS_ASSETS_PATH', CURLY_BUSINESS_ABS_PATH . '/assets');
define('CURLY_BUSINESS_ASSETS_URL_PATH', CURLY_BUSINESS_URL_PATH . 'assets');
define('CURLY_BUSINESS_CPT_PATH', CURLY_BUSINESS_ABS_PATH . '/post-types');
define('CURLY_BUSINESS_SHORTCODES_PATH', CURLY_BUSINESS_ABS_PATH . '/modules/shortcodes');
define('CURLY_BUSINESS_WIDGETS_PATH', CURLY_BUSINESS_ABS_PATH . '/modules/widgets');
define('CURLY_BUSINESS_MODULES_PATH', CURLY_BUSINESS_ABS_PATH . '/modules');